export const Data = [
  {
    id: 1,
    title: 'This is the title',
    podcast: 'Episode 1',
    img: './imgCasts/podcast.jpg',
    date: '01.01.2020',
    info: 'Labore in esse adipisicing aliquip dolor non non commodo pariatur.',
  },
  {
    id: 2,
    title: 'This is the title',
    podcast: 'Episode 2',
    img: './imgCasts/podcast.jpg',
    date: '01.01.2020',
    info: 'Labore in esse adipisicing aliquip dolor non non commodo pariatur.',
  },
  {
    id: 3,
    title: 'This is the title',
    podcast: 'Episode 3',
    img: './imgCasts/podcast.jpg',
    date: '01.01.2020',
    info: 'Labore in esse adipisicing aliquip dolor non non commodo pariatur.',
  },
  {
    id: 4,
    title: 'This is the title',
    podcast: 'Episode 4',
    img: './imgCasts/podcast.jpg',
    date: '01.01.2020',
    info: 'Labore in esse adipisicing aliquip dolor non non commodo pariatur.',
  },
  {
    id: 5,
    title: 'This is the title',
    podcast: 'Episode 5',
    img: './imgCasts/podcast.jpg',
    date: '01.01.2020',
    info: 'Labore in esse adipisicing aliquip dolor non non commodo pariatur.',
  },
  {
    id: 6,
    title: 'This is the title',
    podcast: 'Episode 6',
    img: './imgCasts/podcast.jpg',
    date: '01.01.2020',
    info: 'Labore in esse adipisicing aliquip dolor non non commodo pariatur.',
  },
];
